---
description: sedai detected ailing applications based on traffic
enabled: true
trigger:
  type: core.st2.webhook
  ref: core.08705fb4-a671-4ee0-ad3b-220eca671224
  description: Trigger type for registering webhooks that can consume arbitrary payload.
  parameters:
    url: AILING_APPLICATION_LOAD
action:
  ref: core.local
  description: Action that executes an arbitrary Linux command on the localhost.
  parameters:
    cmd: ls
    timeout: 120
pack: sedai_st2
name: AILING_APPLICATION_LOAD

