---
description: sedai detected ailing instances
enabled: true
trigger:
  type: core.st2.webhook
  ref: core.bb56f882-2880-4a5b-ae14-35ef3b9f5943
  description: Trigger type for registering webhooks that can consume arbitrary payload.
  parameters:
    url: AILING_INSTANCE
action:
  ref: core.local
  description: Action that executes an arbitrary Linux command on the localhost.
  parameters:
    cmd: ls
    timeout: 120
pack: sedai_st2
name: AILING_INSTANCE

