---
description: sedai detected apps ailing based on temporal data.
enabled: true
trigger:
  type: core.st2.webhook
  ref: core.e8b228d9-75c1-4890-8a3b-8bc1f5e63dae
  description: Trigger type for registering webhooks that can consume arbitrary payload.
  parameters:
    url: AILING_APPLICATION_SEASONALITY
action:
  ref: core.local
  description: Action that executes an arbitrary Linux command on the localhost.
  parameters:
    cmd: ls
    timeout: 120
pack: sedai_st2
name: AILING_APPLICATION_SEASONALITY

