---
enabled: true
trigger:
  type: core.st2.webhook
  ref: core.094e9c91-4a7d-4653-8f57-7cf00344e4c2
  description: Trigger type for registering webhooks that can consume arbitrary payload.
  parameters:
    url: UNDEFINED
action:
  ref: core.local
  description: Action that executes an arbitrary Linux command on the localhost.
  parameters:
    cmd: ls
    timeout: 120
pack: sedai_st2
name: UNDEFINED

